// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Assetobj_prefab
    {
        public const string BundleName = "ASSETOBJ_PREFAB";
        public const string ASSETOBJ = "ASSETOBJ";
    }
    public class Furniturepre
    {
        public const string BundleName = "FURNITUREPRE";
        public const string JIAOJI_1 = "JIAOJI_1";
    }
    public class Indoorsceneprefab
    {
        public const string BundleName = "INDOORSCENEPREFAB";
        public const string BEDROOM = "BEDROOM";
        public const string INDOORSCENE = "INDOORSCENE";
        public const string SITTINGROOM = "SITTINGROOM";
    }
    public class Uiconnect_prefab
    {
        public const string BundleName = "UICONNECT_PREFAB";
        public const string UICONNECT = "UICONNECT";
    }
    public class Uidoor_prefab
    {
        public const string BundleName = "UIDOOR_PREFAB";
        public const string UIINDOOR = "UIINDOOR";
    }
    public class Uifurniturelib_prefab
    {
        public const string BundleName = "UIFURNITURELIB_PREFAB";
        public const string UIFURNITURELIB = "UIFURNITURELIB";
    }
    public class Uimainmenu_prefab
    {
        public const string BundleName = "UIMAINMENU_PREFAB";
        public const string UIMAINMENU = "UIMAINMENU";
    }
    public class Uimsg_prefab
    {
        public const string BundleName = "UIMSG_PREFAB";
        public const string UIMSG = "UIMSG";
    }
    public class Uipopupbox_prefab
    {
        public const string BundleName = "UIPOPUPBOX_PREFAB";
        public const string UIPOPUPBOX = "UIPOPUPBOX";
    }
    public class Uitestunirx_prefab
    {
        public const string BundleName = "UITESTUNIRX_PREFAB";
        public const string UITESTUNIRX = "UITESTUNIRX";
    }
}
